Opal 426 - Add function to Weave Pantry object to identify whether a file (identified by hash) already exists in pantry
309thEDDGE/weave pull request #92
Opened 2024-03-25 16:36 UTC by AB-USAF

2024-03-25 17:17 UTC, MJ-USAF submitted a review, later dismissed
This seems to work nicely.

2024-03-25 20:04 UTC, BE-USAF commented on weave/pantry.py
> +            mongo.load_mongo_supplement()
Should we be loading the mongo every time we call this?

2024-03-25 20:08 UTC, BE-USAF requested changes
calling load_mongo_supplement() shouldn't be called every time in here because it takes a lot of time. Let's make this an optional step, or remove.

But this brings up an interesting point. When we call pantry.upload_basket, should we update the mongo dbs with that new item?

2024-03-25 22:09 UTC, BE-USAF approved these changes

2024-03-26 01:30 UTC, MJ-USAF approved these changes

2024-03-26 20:15 UTC, merged