OPAL-549
309thEDDGE/weave pull request #99
Opened 2024-06-10 21:10 UTC by JA-USAF

Add pantry factory

2024-06-11 17:45 UTC, AM-USAF commented on weave/tests/test_pantry_factory.py
> +# Create combinations of the above parameters to pass into the fixture..
Extra period?

2024-06-11 22:26 UTC, hh-usaf submitted a review, later dismissed
I was able to make a pantry the old way and with a config file using create_pantry

2024-06-12 14:01 UTC, AM-USAF commented on weave/pantry_factory.py
> +        file_system = kwargs.pop("file_system")
I get an error here if I only pass in an index and pantry path and no file system

2024-06-12 14:29 UTC, AM-USAF commented on weave/pantry_factory.py
> +    index_type = config["index"]
Should you catch if there is no 'index' in the config file? Same with 'pantry_path' and 'file_system' or are we assuming the user will make their config correctly?

2024-06-12 14:42 UTC, AM-USAF requested changes
Great work! It all works _as expected_ but I think there is more we can do to catch errors for when people are using it not as expected. However, I'm new to all of this so if we don't prioritize that kind of testing on weave and you don't think catching those things is necessary for this ticket, then I am ready to approve.

2024-06-13 16:12 UTC, hh-usaf commented
When I pass an index into create_pantry  with the pantry path but not the file system it still tries to do the third option. Should there be a different error code since the index isn't needed for the third, but the file system is? I may be a little lost

2024-06-13 16:13 UTC, hh-usaf commented
I did not mean to do that

2024-06-13 20:38 UTC, AM-USAF requested changes
Do we need to update the readme with this new factory?

2024-06-13 22:06 UTC, hh-usaf commented on weave/pantry_factory.py
> +        pantry = _create_pantry_from_config(config, **kwargs)
if the pantry does not exist this error is thrown which is not an accurate message for what is happening.

2024-06-17 12:57 UTC, hh-usaf commented on weave/tests/test_pantry_factory.py
> +def test_pantry_factory_default_args(test_pantry):
would it be redundant to make tests with bad variables that are not in the config file?

2024-06-17 13:53 UTC, AM-USAF commented on README.md
> +to enstantiate a pantry:
instantiate

2024-06-17 15:54 UTC, AM-USAF approved these changes

2024-06-17 19:58 UTC, hh-usaf approved these changes

2024-06-17 20:00 UTC, merged